### ISSUE TITLE
Reduce file handle usage when using HDF5 files with external data

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#122]
An issue when we have lots of external files e.g.

```
/entry/data/data_000001  External Link {Finke01_3_3587_data_000001.h5//entry/data/data}
/entry/data/data_000002  External Link {Finke01_3_3587_data_000002.h5//entry/data/data}
...
/entry/data/data_001520  External Link {Finke01_3_3587_data_001520.h5//entry/data/data}
/entry/data/data_001521  External Link {Finke01_3_3587_data_001521.h5//entry/data/data}
```

dials.import crashes:

```
Grey-Area imp :) $ dials.import ../Finke01_3_3587_master.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1157-g22f7186fa
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 884, in <module>
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 724, in run
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 847, in parse_args
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 564, in parse_args
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 230, in __init__
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 303, in try_read_experiments_from_images
  File "/Users/graeme/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 495, in from_filenames
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1529, in from_filenames
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 965, in __init__
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1185, in _create_single_file_imageset
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 155, in get_imageset
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 25, in __init__
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 41, in read_num_images
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 264, in get_instance
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatHDF5.py", line 15, in __init__
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 155, in __init__
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 165, in setup
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 349, in _start
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 1777, in __init__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Please report this error to dials-support@lists.sourceforge.net: Unable to open object (unable to open external file, external link file name = 'Finke01_3_3587_data_000249.h5')"
```

I think an issue here is we open and save a handle from every data brick in the (nearly) NeXus reading code when really we should not. I have not assessed how much cost or benefit this brings. On import we probably do need to inspect each to make sure that the data are present. 

N.B. this is a dxtbx feature / bug because 

```
import sys
from dxtbx.model.experiment_list import ExperimentListFactory
experiments = ExperimentListFactory.from_filenames(sys.argv[1:])
imagesets = experiments.imagesets()
print len(experiments), len(imagesets)

for e in experiments:
    print e.scan

print imagesets[0].get_scan()
```

crashes in a very similar way.

**Comment by graeme-winter** [comment]
Looks like the area to blame is `DataFactory` where we open a lot of handles and keep them all:

https://github.com/cctbx/dxtbx/blob/83768793888223344f8f5c28daece6d289f10903/format/nexus.py#L1767

**Comment by Anthchirp** [comment]
started a branch [datafactory](https://github.com/dials/dxtbx/compare/master...cctbx:datafactory?expand=1) with related changes.

**Comment by biochem-fan** [comment]
To provide a historical context:

This workaround was introduced because h5py does not allow creation of links to read-only files 
https://github.com/h5py/h5py/issues/467. See also discussions in dials-support around 2016 Feb-Mar. Indeed, deferring file opening sounds a better implementation.

**Comment by Anthchirp** [comment]
What I could find out so far:

We are very prolific with file handles and not very efficient in reading data from many .h5 files.
Running `dials.import` on the fileset above we
* open and close each .h5 file once
* open and close each .h5 file once more
* open and close each .h5 file again
* open all .h5 files. This of course fails, but all errors are caught. Not just in the first layer but actually 7 layers deep (ie. essentially `try: try: try: ... except: pass except: pass except: pass`). We record all the errors in an array which we apparently then don't look at. Then we close all files.
* we then do the same thing again.
* and again.
* and once more.
* then we open all the files at the same time, but this time without the 7-fold-try-catch. This is the step where we crash.

**Comment by Anthchirp** [comment]
Partial traces for those 8 operations:

1.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 313, in _start
  fixer = EigerNXmxFixer(self._image_file, temp_file)
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 133, in __init__
  handle_orig["/entry/data/%s" % k].shape
```

2.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 313, in _start
  fixer = EigerNXmxFixer(self._image_file, temp_file)
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 264, in __init__
  num_images += len(handle_orig["/entry/data/%s" % name])
```

3.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 313, in _start
  fixer = EigerNXmxFixer(self._image_file, temp_file)
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 293, in __init__
  filename = handle_orig["entry/data"][name].file.filename
```

4.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 314, in _start
  reader = NXmxReader(handle=fixer.handle)
File "dxtbx/format/nexus.py", line 904, in __init__
  for entry in find_entries(handle, "/"):
File "dxtbx/format/nexus.py", line 221, in find_entries
  local_visit(nx_file, visitor)
File "dxtbx/format/nexus.py", line 199, in local_visit
  local_visit(k, visitor)
File "dxtbx/format/nexus.py", line 199, in local_visit
  local_visit(k, visitor)
File "dxtbx/format/nexus.py", line 194, in local_visit
  for k in nxfile.values():
```

5.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 314, in _start
  reader = NXmxReader(handle=fixer.handle)
File "dxtbx/format/nexus.py", line 906, in __init__
  self.entries.append(NXmxEntry(entry, errors=self.errors))
File "dxtbx/format/nexus.py", line 855, in __init__
  for entry in find_class(self.handle, "NXinstrument"):
File "dxtbx/format/nexus.py", line 237, in find_class
  local_visit(nx_file, visitor)
File "dxtbx/format/nexus.py", line 199, in local_visit
  local_visit(k, visitor)
File "dxtbx/format/nexus.py", line 194, in local_visit
  for k in nxfile.values():
```

6.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 314, in _start
  reader = NXmxReader(handle=fixer.handle)
File "dxtbx/format/nexus.py", line 906, in __init__
  self.entries.append(NXmxEntry(entry, errors=self.errors))
File "dxtbx/format/nexus.py", line 864, in __init__
  for entry in find_class(self.handle, "NXsample"):
File "dxtbx/format/nexus.py", line 237, in find_class
  local_visit(nx_file, visitor)
File "dxtbx/format/nexus.py", line 199, in local_visit
  local_visit(k, visitor)
File "dxtbx/format/nexus.py", line 194, in local_visit
  for k in nxfile.values():
```

7.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 314, in _start
  reader = NXmxReader(handle=fixer.handle)
File "dxtbx/format/nexus.py", line 906, in __init__
  self.entries.append(NXmxEntry(entry, errors=self.errors))
File "dxtbx/format/nexus.py", line 873, in __init__
  for entry in find_class(self.handle, "NXdata"):
File "dxtbx/format/nexus.py", line 237, in find_class
  local_visit(nx_file, visitor)
File "dxtbx/format/nexus.py", line 199, in local_visit
  local_visit(k, visitor)
File "dxtbx/format/nexus.py", line 194, in local_visit
  for k in nxfile.values():
```

8.
```python
File "dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 348, in _start
  self._raw_data = datafactory(data)
File "dxtbx/format/nexus.py", line 1811, in datafactory
  datasets = DataSetProxy(obj)
File "dxtbx/format/nexus.py", line 1777, in __init__
  if obj.handle[key].ndim == 1:
```

**Comment by Anthchirp** [comment]
I've eliminated 2, 3, and fixed the crash in 8. I am not convinced 4-7 are necessary or useful, so want to look into that. Before merging in the changes I'll also need to validate that the workaround A. is still required and B. still works.

**Comment by Anthchirp** [comment]
I believe I have identified the place where we open the HDF5 files in write mode (which we shouldn't be doing anyway), so the workaround may no longer be required. Bad news is that overall the changes are very complex so won't make the 2.0.3 release.
