### ISSUE TITLE
dxtbx does not like files named *0000.cbf

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#133]
```
$ dials.find_spots 0001.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.1.1-gcdd629a7b-release
(...)
Found 0 strong pixels on image 1
(...)
Saved 0 reflections to strong.refl
Time Taken: 0.740225


$ cp 0001.cbf 0000.cbf


$ dials.find_spots 0000.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.1.1-gcdd629a7b-release
The following parameters have been modified:

input {
  experiments = <image files>
}

Setting spotfinder.filter.min_spot_size=3
Configuring spot finder from input parameters
--------------------------------------------------------------------------------
Finding strong spots in imageset 0
--------------------------------------------------------------------------------


Finding spots in image 0 to 0...
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v2-1-1/build/../modules/dials/command_line/find_spots.py", line 196, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v2-1-1/build/../modules/dials/command_line/find_spots.py", line 128, in run
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/dls_sw/apps/dials/dials-v2-1-1/modules/dials/array_family/flex.py", line 198, in from_observations
    return find_spots(experiments)
  File "/dls_sw/apps/dials/dials-v2-1-1/modules/dials/algorithms/spot_finding/finder.py", line 764, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/dls_sw/apps/dials/dials-v2-1-1/modules/dials/algorithms/spot_finding/finder.py", line 870, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/dls_sw/apps/dials/dials-v2-1-1/modules/dxtbx/imageset.py", line 234, in __getitem__
    return self.partial_set(start - offset, stop - offset)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /dls_sw/apps/dials/dials-v2-1-1/modules/dxtbx/imageset.h(936): DXTBX_ASSERT(index < indices_.size()) failure.
```

**Comment by dagewa** [comment]
I note that the experiment apparently _imports_ just fine and can be passed into `dials.show` or `dials.image_viewer`, but not `dials.find_spots`
