### ISSUE TITLE
ExperimentList.from_file fails obscurely when image data are missing

### ISSUE THREAD

**Issue by dagewa** [cctbx/dxtbx#154]
```
>>> from dxtbx.model import ExperimentList
>>> el=ExperimentList.from_file('indexed.expt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/__init__.py", line 846, in from_file
    return ExperimentListFactory.from_serialized_format(filename, check_format)
  File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 750, in from_serialized_format
    return ExperimentListFactory.from_pickle_file(filename)
  File "/home/fcx32934/sw/cctbx/modules/dxtbx/model/experiment_list.py", line 714, in from_pickle_file
    obj = pickle.load(infile)
_pickle.UnpicklingError: invalid load key, '{'.
```
seems to be for pickles only?

**Comment by dagewa** [comment]
probably due to missing images in this case

**Comment by dagewa** [comment]
Yes, missing images. A clearer error would be useful
```
>>> ExperimentList.from_file("indexed.expt",check_format=False)
ExperimentList([<dxtbx_model_ext.Experiment object at 0x7fe2335d1120>, <dxtbx_model_ext.Experiment object at 0x7fe22954cd50>])
```

**Comment by rjgildea** [comment]
I think we probably need to catch a specific `FileNotFoundError` here and re-raise this to avoid swallowing these error?
https://github.com/cctbx/dxtbx/blob/bbb9f7eb50340811f1a3b942fb0eb416fa0218c5/model/experiment_list.py#L744-L747

**Comment by dagewa** [comment]
Yes, sounds right
