### ISSUE TITLE
Jungfrau rotation data unreadable: AssertionError: Please report this error to dials-support@lists.sourceforge.net: Couldn't match dataset data_000001 to a NXdetector

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#251]
```
Grey-Area psi-jf-4m :) $ dials.image_viewer thau2_12p4keV_1p0T_10DPS_1KHz_FW2_1_master.h5
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 207, in <module>
    run()
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/image_viewer.py", line 183, in run
    params, options = parser.parse_args(args, show_diff_phil=True)
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 841, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 546, in parse_args
    importer = Importer(
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 205, in __init__
    self.unhandled = self.try_read_experiments_from_images(
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 276, in try_read_experiments_from_images
    experiments = ExperimentListFactory.from_filenames(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 525, in from_filenames
    for db in DataBlockFactory.from_filenames(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1489, in from_filenames
    importer = DataBlockFilenameImporter(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 934, in __init__
    imageset = self._create_single_file_imageset(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1153, in _create_single_file_imageset
    return format_class.get_imageset(abspath(filename), format_kwargs=format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImageLazy.py", line 31, in get_imageset
    return super(FormatMultiImageLazy, Class).get_imageset(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 147, in get_imageset
    format_instance = cls(filenames[0], **format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatHDF5.py", line 15, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 137, in __init__
    self.setup()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatStill.py", line 22, in setup
    self._start()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatNexus.py", line 82, in _start
    self._raw_data = detectorgroupdatafactory(data, instrument)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 1447, in detectorgroupdatafactory
    assert found_it, "Couldn't match dataset %s to a NXdetector" % dataset_name
AssertionError: Please report this error to dials-support@lists.sourceforge.net: Couldn't match dataset data_000001 to a NXdetector
```

This apparently used to work from June 2020 so something recent may have broken it...

**Comment by graeme-winter** [comment]
Additional: commit 442d8a0d1f0425fcef35d364fc339a351b949b63 broke this

**Comment by graeme-winter** [comment]
Possibly pertinent: `/entry/instrument/detector/data Soft Link {/entry/data/data_000001}` in the master file

**Comment by phyy-nx** [comment]
I didn't have access to a soft linked dataset. Might need an if statement here of some kind.

**Comment by graeme-winter** [comment]
@phyy-nx yeh no problem I am just working through the logic of what this is trying to do to figure out a nice solution - the easy one is to add essentially _both_ methods but that would be pretty ugly. Maybe though it is quick & easy enough to be good enough here, despite being ugly.

**Comment by graeme-winter** [comment]
Also the `found_it` flag makes me 😖

**Comment by graeme-winter** [comment]
Additional: if I revert the commit mentioned above I find that the data are imported as a set of still images not an image sequence:

```
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexusStill'>
  num images: 3600
  sequences:
    still:    0
    sweep:    0
  num stills: 3600
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

so yes some more work is needed here

**Comment by graeme-winter** [comment]
Does appear to be missing the `omega_increment` data set which is expected under NXmx?

**Comment by dagewa** [comment]
Nobody rushing in support of this issue, will close
