### ISSUE TITLE
Eiger 4m @ ESRF no longer works

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#27]
```
[gw56@cs03r-sc-serv-16 esrf-eiger-4m]$ dials.import thaumatin28_w1_3_1_master.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.325-g14f9423
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 909, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 907, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 751, in run
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 838, in parse_args
    quick_parse=quick_parse,
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 550, in parse_args
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 229, in __init__
    format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 295, in try_read_experiments_from_images
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 676, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/datablock.py", line 1076, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/datablock.py", line 534, in __init__
    fmt, filename, format_kwargs=format_kwargs
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/datablock.py", line 729, in _create_single_file_imageset
    return format_class.get_imageset(abspath(filename), format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 188, in get_imageset
    reader = Class.get_reader()(filenames, num_images=num_images, **format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 14, in __init__
    self._num_images = self.read_num_images()
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 30, in read_num_images
    format_instance = self.format_class.get_instance(self._filename, **self.kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/Format.py", line 313, in get_instance
    Class._current_instance_ = Class(filename, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 313, in __init__
    FormatHDF5.__init__(self, image_file, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatHDF5.py", line 18, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/Format.py", line 203, in __init__
    self.setup()
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/Format.py", line 213, in setup
    self._start()
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 369, in _start
    for f0, f1, s0, s1 in determine_eiger_mask(self._detector_model):
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatPilatusHelpers.py", line 170, in determine_eiger_mask
    assert (n_fast - 1) * gap_size_fast == remainder
AssertionError: Please report this error to dials-support@lists.sourceforge.net:
```

reported by @dagewa

**Comment by graeme-winter** [comment]
Related to https://github.com/cctbx/cctbx_project/commit/a1ea22a18b4251ede9a943f81c1e79928aed53d5?

**Comment by graeme-winter** [comment]
Detectors in different parts of France have different opinions re: fast, slow directions

**Comment by graeme-winter** [comment]
```
[gw56@cs03r-sc-serv-16 9]$ dials.import /dls/mx-scratch/rjgildea/zenodo/1221344/200Hz/3_5_200Hz_1_master.h5
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.340-g5a84c27
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 909, in <module>
    halraiser(e)
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 907, in <module>
    script.run()
  File "/dls/science/users/gw56/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 751, in run
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 838, in parse_args
    quick_parse=quick_parse,
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 550, in parse_args
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 229, in __init__
    format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dials/util/options.py", line 295, in try_read_experiments_from_images
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 676, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/datablock.py", line 1076, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/datablock.py", line 534, in __init__
    fmt, filename, format_kwargs=format_kwargs
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/datablock.py", line 729, in _create_single_file_imageset
    return format_class.get_imageset(abspath(filename), format_kwargs=format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 188, in get_imageset
    reader = Class.get_reader()(filenames, num_images=num_images, **format_kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 14, in __init__
    self._num_images = self.read_num_images()
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 30, in read_num_images
    format_instance = self.format_class.get_instance(self._filename, **self.kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/Format.py", line 314, in get_instance
    Class._current_instance_ = Class(filename, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 313, in __init__
    FormatHDF5.__init__(self, image_file, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatHDF5.py", line 18, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/Format.py", line 204, in __init__
    self.setup()
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/Format.py", line 214, in setup
    self._start()
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatHDF5EigerNearlyNexus.py", line 369, in _start
    for f0, f1, s0, s1 in determine_eiger_mask(self._detector_model):
  File "/dls/science/users/gw56/svn/cctbx/modules/dxtbx/format/FormatPilatusHelpers.py", line 170, in determine_eiger_mask
    assert (n_fast - 1) * gap_size_fast == remainder
AssertionError: Please report this error to dials-support@lists.sourceforge.net:

```

Fixing this will either cause 😵 or technical debt, the only way to win is not to play

**Comment by graeme-winter** [comment]
```
cs03r-sc-serv-16 esrf-eiger-4m :) $ dials.import thaumatin28_w1_3_1_master.h5
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.780-gffe37ced6
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatHDF5EigerNearlyNexus.FormatHDF5EigerNearlyNexus'>
  num images: 100
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

ESRF one works

```
Grey-Area x :) $ dials.import ../200Hz_0.1dpf_1_master.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.780-gffe37ced6
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatHDF5EigerNearlyNexus.FormatHDF5EigerNearlyNexus'>
  num images: 1800
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
```

One from Soleil Eiger 9M works

🦍 of "temporary" workarounds wins.
