### ISSUE TITLE
cbf_writer

### ISSUE THREAD

**Issue by dagewa** [cctbx/dxtbx#278]
I found this thing under `format/`. Is it supposed to work? It seems it does not in my hands.
```
$ dials.python /home/fcx32934/sw/cctbx/modules/dxtbx/format/cbf_writer.py imported.expt 
Traceback (most recent call last):
  File "/home/fcx32934/sw/cctbx/modules/dxtbx/format/cbf_writer.py", line 582, in <module>
    writer = FullCBFWriter(filename=filename)
  File "/home/fcx32934/sw/cctbx/modules/dxtbx/format/cbf_writer.py", line 38, in __init__
    imageset = format_class.get_imageset([filename])
AttributeError: 'NoneType' object has no attribute 'get_imageset'
```

**Comment by dagewa** [comment]
@rjgildea points out that this script works if passed an image file, but not a `.expt`. I should have tried that...

Perhaps some improvements can be made to this jiffy:
- adding `.expt` read
- supporting scans and goniometers 
- moving from `format/` to `command_line/` to make `dxtbx.convert_to_cbf`
- add tests

**Comment by phyy-nx** [comment]
The cbf_writer is used by cctbx.xfel.xtc_process (mostly deprecated at this point) and by dxtbx.image_average.  The latter is tested by test/command_line/test_average.py.  That test isn't run on azure because xfel isn't configured on the dxtbx Azure builds and the averager uses some xfel modules.

**Comment by dagewa** [comment]
I have a use case for this now, and I should be able to pick this up without affecting the call by `dxtbx.image_average`. I would like to move the code out of `format/` though

**Comment by phyy-nx** [comment]
👍

**Comment by dagewa** [comment]
There's a bug here if gain ≠ 1: the converted CBF seems to have the corrected image values of the original image written as the raw image values.

**Comment by phyy-nx** [comment]
Yup, this is the utility for creating arbitrary ImageCIF from any dxtbx format, and it is missing scans and gonios.  Also, I should note that cbf_writer is used by nanoBragg as well.

Regarding the point on gain above, I bumped into this a week or so ago when dumping some cbfs from LCLS data.  I strongly suspect I'll be wanting to add this diff to cbf_writer soon to avoid writing out corrected data and avoid double dividing by gain during processing:

```
$ git diff cbf_writer.py
diff --git a/src/dxtbx/format/cbf_writer.py b/src/dxtbx/format/cbf_writer.py
index c52c296f..a3b9863d 100644
--- a/src/dxtbx/format/cbf_writer.py
+++ b/src/dxtbx/format/cbf_writer.py
@@ -471,9 +471,9 @@ class FullCBFWriter:
         """
         if data is None:
             if index is None:
-                data = self.imageset[0]
+                data = self.get_raw_data(0)
             else:
-                data = self.imageset[index]
+                data = self.get_raw_data(index)
         if not isinstance(data, tuple):
             data = (data,)
```

**Comment by dagewa** [comment]
Great, I assigned us both here for the various tasks above :)

**Comment by phyy-nx** [comment]
(edited above comment to correct it, should be `self.imageset.get_raw_data`

**Comment by dagewa** [comment]
@phyy-nx is this thing kind of made obsolete by `dxtbx.any2nexus`?

**Comment by phyy-nx** [comment]
Nope, dxtbx.image_average shouldn't create NeXus files in my opinion since the averages are always single images.  NeXus seems overkill to me for that.
