### ISSUE TITLE
FormatNexusJungfrauExt breaks regression tests

### ISSUE THREAD

**Issue by ndevenish** [cctbx/dxtbx#321]
Looks like the change from #303 adding `FormatNexusJungfrauExt.py` caused a failure somewhere in the regression checks:
```
In tests.test_regression_images.test_format_class_API_assumptions[putative_imgCIF_HDF5_mapping/X4_wide_M1S4_1.nxs]

Error Message
KeyError: "Unable to open object (object 'name' doesn't exist)"
Stacktrace
test_image = '/dls/science/groups/scisoft/DIALS/repositories/git-reference/dials_regression/image_examples/putative_imgCIF_HDF5_mapping/X4_wide_M1S4_1.nxs'

    def test_format_class_API_assumptions(test_image):
        """For a given image file, walk the whole DAG of Format objects, and
        verify the following basic assumptions for format classes:
        * Any file must only be understood by a single leaf node format class.
        * No .understand() call on any top level format class or a child class
          of another understanding format is allowed to throw an exception.
        """
        if six.PY3 and test_image.endswith(".pickle"):
            pytest.skip("Importing .pickle format images is not supported in Python 3")
    
        dag = dxtbx.format.Registry.get_format_class_dag()
    
        def recurse(parentformat, filename, level=0):
            known_format_class = None
            multiple_formats = False
            for subformat in dag.get(parentformat, []):
                format_class = dxtbx.format.Registry.get_format_class_for(subformat)
                if not get_url_scheme(filename) in format_class.schemes:
                    print("Not matching ", filename, "to", format_class)
                    continue
                understood = format_class.understand(filename)
                print("%s%s: %s" % ("  " * level, subformat, understood))
                if understood:
                    recursive_format_class, subtree_multiple = recurse(
                        subformat, filename, level + 1
                    )
                    understood_format_class = recursive_format_class or subformat
                    if known_format_class and known_format_class != understood_format_class:
                        print(
                            "File can be understood as %s and %s"
                            % (known_format_class, understood_format_class)
                        )
                        multiple_formats = True
                    known_format_class = understood_format_class
                    multiple_formats |= subtree_multiple
            return known_format_class, multiple_formats
    
>       understood_format, multiple_formats = recurse("Format", test_image)

../build_dials/modules/dxtbx/tests/test_regression_images.py:276: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../build_dials/modules/dxtbx/tests/test_regression_images.py:262: in recurse
    recursive_format_class, subtree_multiple = recurse(
../build_dials/modules/dxtbx/tests/test_regression_images.py:262: in recurse
    recursive_format_class, subtree_multiple = recurse(
../build_dials/modules/dxtbx/tests/test_regression_images.py:259: in recurse
    understood = format_class.understand(filename)
../build_dials/modules/dxtbx/format/FormatNexusJungfrauExt.py:47: in understand
    if handle["/entry/instrument/name"][()] != "SwissFEL ARAMIS BEAMLINE ESB":
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
../build_dials/conda_base/lib/python3.8/site-packages/h5py/_hl/group.py:288: in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   KeyError: "Unable to open object (object 'name' doesn't exist)"
```

**Comment by graeme-winter** [comment]
These files I don't think ever matched "NXmx" standard properly (certainly not the "gold standard") however would probably be good if they did not fail in this way. I'll take a quick look now.

**Comment by graeme-winter** [comment]
```
Silver-Surfer format :) [master] $ git diff
diff --git a/format/FormatNexusJungfrauExt.py b/format/FormatNexusJungfrauExt.py
index dedd79a..3d3df8e 100644
--- a/format/FormatNexusJungfrauExt.py
+++ b/format/FormatNexusJungfrauExt.py
@@ -43,7 +43,10 @@ class FormatNexusJungfrauExt(FormatNexus):
         if "xfel" not in sys.modules:
             return False
         with h5py.File(image_file, "r") as handle:
-            # Note, in the future this class might support more instruments, for now it is tested with the SwissFEL one
+            # Note, in the future this class might support more instruments,
+            # for now it is tested with the SwissFEL one
+            if not "name" in handle["/entry/instrument"]:
+                return False
             if handle["/entry/instrument/name"][()] != "SwissFEL ARAMIS BEAMLINE ESB":
                 return False
```

Applying this patch _does not_ fix the problem - however this then fails with code outside `FormatNexusJungfrauExt.py` - 

```
Silver-Surfer tmp :( $ dials.import X4_wide_M1S4_1.nxs 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.385-gaada31939
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 951, in <module>
    run()
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 947, in run
    importer.import_image(args)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 783, in import_image
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 827, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 535, in parse_args
    importer = Importer(
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 196, in __init__
    self.unhandled = self.try_read_experiments_from_images(
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 267, in try_read_experiments_from_images
    experiments = ExperimentListFactory.from_filenames(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 516, in from_filenames
    for db in DataBlockFactory.from_filenames(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1482, in from_filenames
    importer = DataBlockFilenameImporter(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 928, in __init__
    imageset = self._create_single_file_imageset(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1149, in _create_single_file_imageset
    return format_class.get_imageset(
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 163, in get_imageset
    format_instance = cls.get_instance(filenames[0], **format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 271, in get_instance
    Class._current_instance_ = Class(filename, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatHDF5.py", line 16, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 165, in __init__
    self.setup()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 175, in setup
    self._start()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatNexus.py", line 24, in _start
    self._reader = reader = nexus.NXmxReader(self._image_file)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 485, in __init__
    self.entries.append(NXmxEntry(entry))
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 467, in __init__
    self.instruments = [NXinstrument(instrument) for instrument in instruments]
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 467, in <listcomp>
    self.instruments = [NXinstrument(instrument) for instrument in instruments]
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 411, in __init__
    self.detectors = [NXdetector(detector) for detector in detectors]
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 411, in <listcomp>
    self.detectors = [NXdetector(detector) for detector in detectors]
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 391, in __init__
    raise NXValidationError("No NXdetector_module in %s" % self.handle.name)
dxtbx.format.nexus.NXValidationError: Please report this error to dials-support@lists.sourceforge.net: No NXdetector_module in /entry/instrument/detector
```

I'm not sure why this now fails when it (apparently) used to be OK

**Comment by graeme-winter** [comment]
```
/detector                Group
    Attribute: NX_class scalar
        Type:      11-byte null-terminated ASCII string
        Data:  "NXdetector"
    Location:  1:7416
    Links:     1
```

🤔

**Comment by graeme-winter** [comment]
FWIW I get the same error in the 3.3.2 DIALS release

**Comment by graeme-winter** [comment]
@ndevenish am tempted to close this one & remove the offending data set from the regression tests - the PR above is probably not a bad idea to include (if thing not there, cannot be equal to whatever) but other than that I think this is unlikely to be useful.

**Comment by phyy-nx** [comment]
I generally agree. The cspad to nexus line of work never really finished and is obviated by FormatXTCCspad.
