### ISSUE TITLE
Add dxtbx Azure builds for Windows

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#396]
Getting this to run using pre-built cctbx will take some time, but ultimately would be very useful to have.

**Comment by Anthchirp** [comment]
Had a go at another build attempt against cctbx 2021.7 (due to conda-forge/cctbx-base-feedstock#28 blocker) on the windows-build branch.

This still doesn't work as apparently some cctbx build mechanism has drastically changed. The build step is now a NOP, and libtbx dispatchers are missing from the `build/bin` directory 
```
Setting up build directory
Running D:\a\1\conda_base\python.exe ..\modules\cctbx_project\libtbx\configure.py --skip_phenix_dispatchers cctbx cbflib dxtbx scitbx libtbx iotbx --compiler=conda --enable_cxx11 --use_conda (in build)
(via conda environment) libtbx.scons
Running cmd.exe /C indirection.cmd libtbx.scons.bat -j 2 (in build)
(via conda environment) libtbx.scons
Running cmd.exe /C indirection.cmd libtbx.scons.bat -j 2 (in build)
Running libtbx.refresh
Running build\bin\libtbx.refresh.bat (in .)
Traceback (most recent call last):
  File "modules/dxtbx/.azure-pipelines/bootstrap.py", line 156, in run_command
    p = subprocess.Popen(args=command, cwd=workdir, env=clean_env)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by rjgildea** [comment]
These now fail with a _different_ error:
```
Processing: "d:\a\1\modules\dxtbx\libtbx_refresh.py"
Traceback (most recent call last):
  File "..\modules\cctbx_project\libtbx\configure.py", line 34, in <module>
    if not run():
  File "..\modules\cctbx_project\libtbx\configure.py", line 29, in run
    libtbx.env_config.cold_start(sys.argv)
  File "D:\a\1\modules\cctbx_project\libtbx\env_config.py", line 3038, in cold_start
    env.refresh()
  File "D:\a\1\modules\cctbx_project\libtbx\env_config.py", line 2266, in refresh
    self.generate_entry_point_dispatchers()
  File "D:\a\1\modules\cctbx_project\libtbx\env_config.py", line 2111, in generate_entry_point_dispatchers
    paths = {self.get_setuptools_script_dir()}
  File "D:\a\1\modules\cctbx_project\libtbx\env_config.py", line 2057, in get_setuptools_script_dir
    command = dist.get_command_obj('install')
  File "D:\a\1\conda_base\lib\site-packages\setuptools\_distutils\dist.py", line 860, in get_command_obj
bj = self.command_obj[command] = klass(self)
  File "D:\a\1\conda_base\lib\distutils\cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
```
I don't know whether this is earlier or later in the build process than the previous error...
