### ISSUE TITLE
Cope gracefully with Format classes which include uninstalled dependencies

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#407]
If a Format class is available with undeclared dependencies, it crashes the task - which is probably not what we want if the format class was not going to be used anyway. 

Options:
 - cope gracefully with failing e.g. when imported / accessed via entrypoint catch and warn
 - ensure in a programmatic manner that all undeclared dependencies are installed

The latter _could_ be a superior option - obviously the ideal would be to have all dependencies properly declared.

**Comment by graeme-winter** [comment]
The latter would have to use AST as part of the entry point registration?

**Comment by graeme-winter** [comment]
```
Grey-Area demo :) $ dials.import ../xtal_1_5.nxs 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 3.dev.525-g2014f815b
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/dials_import.py", line 951, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/dials_import.py", line 947, in run
    importer.import_image(args)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/dials_import.py", line 782, in import_image
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/Users/graeme/git/dials/modules/dials/util/options.py", line 826, in parse_args
    params, args = self._phil_parser.parse_args(
  File "/Users/graeme/git/dials/modules/dials/util/options.py", line 534, in parse_args
    importer = Importer(
  File "/Users/graeme/git/dials/modules/dials/util/options.py", line 196, in __init__
    self.unhandled = self.try_read_experiments_from_images(
  File "/Users/graeme/git/dials/modules/dials/util/options.py", line 267, in try_read_experiments_from_images
    experiments = ExperimentListFactory.from_filenames(
  File "/Users/graeme/git/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 546, in from_filenames
    format_class = find_format.find_format(filename)
  File "/Users/graeme/git/dials/modules/dxtbx/src/dxtbx/datablock.py", line 312, in find_format
    self._format_class = get_format_class_for_file(filename)
  File "/Users/graeme/git/dials/modules/dxtbx/src/dxtbx/format/Registry.py", line 125, in get_format_class_for_file
    return recurse(format, image_file)
  File "/Users/graeme/git/dials/modules/dxtbx/src/dxtbx/format/Registry.py", line 116, in recurse
    return recurse(child, image_file)
  File "/Users/graeme/git/dials/modules/dxtbx/src/dxtbx/format/Registry.py", line 114, in recurse
    format_class = get_format_class_for(child)
  File "/Users/graeme/git/dials/modules/dxtbx/src/dxtbx/format/Registry.py", line 28, in get_format_class_for
    return get_format_class_index()[format_class_name][0]()
  File "/Users/graeme/git/dials/conda_base/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/Users/graeme/git/dials/conda_base/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/graeme/git/dials/modules/dlstbx/src/dlstbx/format/FormatNXmx.py", line 2, in <module>
    import foobar
ModuleNotFoundError: No module named 'foobar'
```

illustration of the error in question

**Comment by dagewa** [comment]
The approach I usually take is to wrap the import in `try` and fail to `understand` if the dependency is not available. For example, https://github.com/dials/dxtbx_ED_formats/blob/main/FormatTIFFgeneric.py
