### ISSUE TITLE
FormatHDF5SaclaMPCCD fails to identify empty files

### ISSUE THREAD

**Issue by ndevenish** [cctbx/dxtbx#427]
A user case trying to reprocess with stills_process:
```
Have 1 files
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Loading files...
Loading run10XXXX-0.h5
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Abort: Could not load /path/to/run10XXXX-0.h5
```

Upon inspection, this file has a `/metadata` key but no `/tag-*` data. Looking at the format class, the criteria for understanding is:
- IF it has a `/metadata/detector` key, that it is _not_ "Rayonix"
- at least one `/tag-*` key
https://github.com/cctbx/dxtbx/blob/b28a69ff650254940c30c66da4982c2a847f6384/src/dxtbx/format/FormatHDF5SaclaMPCCD.py#L44-L53

It might be that it's just too generic without the `tag-`, but is any of the metadata structure unique enough to identify as a file without data?

**Comment by phyy-nx** [comment]
I would guess the crash is on line 46 or 47 if there is a unicode error.  If you run dials.show on the h5 file do you get the full traceback?

**Comment by ndevenish** [comment]
No, the unicode error comes because it fails to match any (non-abstract) Format class, and so dxtbx tries to interpret it as an "Experiment List". We've run into this occasionally before, but I think we always fixed it closer to the source rather than leaving experimentlist parsing as the final resort. I'm not sure whether "finding" the h5 file should block further parsing, especially if we're considering using it for reflections. `dials.show` does however show the full stack trace:
```
Sorry: Unable to handle the following arguments:
  "/dls/x02-1/data/2021/mx15722-31/cheetah_test_sugimoto/103638-0/run103638-0.h5" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/dls_sw/apps/dials/dials-v3-6-0-1/modules/dials/util/options.py", line 300, in try_read_experiments
        data=ExperimentListFactory.from_json_file(
      File "/dls_sw/apps/dials/dials-v3-6-0-1/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 778, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/dls_sw/apps/dials/dials-v3-6-0-1/build/../conda_base/lib/python3.9/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

This format class fails to match because there is only a `/metadata` group, no `/tag-` groups, so drops off the end of the line 50 loop

**Comment by phyy-nx** [comment]
Ok thanks, that makes sense.  I don't think we have an established error pathway for 'this container has no data'.  Even if we could examine the metadata and decide it's a FormatHDF5SaclaMPCCD, get_num_images would be zero so would it be useful?

Granted the error that you got is not useful :)
