### ISSUE TITLE
DXTBX_ASSERT(start[i] + count[i] <= dataset_dims[i])

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#52]
3 image screening dataset.
`dials.import` followed by `dials.find_spots` works for 2 images, on 3rd image:

```
Traceback (most recent call last):
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/find_spots.py", line 223, in <module>
    halraiser(e)
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/find_spots.py", line 221, in <module>
    script.run()
  File "/scratch/wra62962/files/dials/build/../modules/dials/command_line/find_spots.py", line 152, in run
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/scratch/wra62962/files/dials/modules/dials/array_family/flex.py", line 211, in from_observations
    return find_spots(experiments)
  File "/scratch/wra62962/files/dials/modules/dials/algorithms/spot_finding/finder.py", line 770, in __call__
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/scratch/wra62962/files/dials/modules/dials/algorithms/spot_finding/finder.py", line 867, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/scratch/wra62962/files/dials/modules/dials/algorithms/spot_finding/finder.py", line 478, in __call__
    return self._find_spots(imageset)
  File "/scratch/wra62962/files/dials/modules/dials/algorithms/spot_finding/finder.py", line 586, in _find_spots
    result = function(task)
  File "/scratch/wra62962/files/dials/modules/dials/algorithms/spot_finding/finder.py", line 115, in __call__
    image = self.imageset.get_corrected_data(index)
  File "/scratch/wra62962/files/dials/modules/dxtbx/format/FormatMultiImage.py", line 31, in read
    return format_instance.get_raw_data(index)
  File "/scratch/wra62962/files/dials/modules/dxtbx/format/FormatNexus.py", line 131, in get_raw_data
    return self._raw_data[index]
  File "/scratch/wra62962/files/dials/modules/dxtbx/format/nexus.py", line 1591, in __getitem__
    (slice(i, i + 1, 1), slice(0, height, 1), slice(0, width, 1)),
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /scratch/wra62962/files/dials/modules/dxtbx/format/boost_python/nexus_ext.cc(55): DXTBX_ASSERT(start[i] + count[i] <= dataset_dims[i]) failure.
```

presumably this is #19?

**Comment by graeme-winter** [comment]
Verified on fruiter but think this is distinct from #19

**Comment by Anthchirp** [comment]
have 4 more examples of this from I03 within the last day

**Comment by graeme-winter** [comment]
```
      std::cerr << start[i] << "\t" << count[i] << "\t" << dataset_dims[i] << std::endl;
      DXTBX_ASSERT(start[i] + count[i] <= dataset_dims[i]);
```

gives 

```
2	1	2
Traceback (most recent call last):
```

3 image data set has slowest dimension 2?

**Comment by graeme-winter** [comment]
Code is right; data are wrong

```
Grey-Area dxtbx-52 :) $ ~/svn/cctbx/base/bin/h5ls -r RPTP-F6-63_1_000001.h5 
/                        Group
/data                    Dataset {2/Inf, 4362, 4148}
```

**Comment by Anthchirp** [comment]
-> MXGDA-3335
