### ISSUE TITLE
Regression in Eiger 9M support compared with dials 3.8: data dimensions

### ISSUE THREAD

**Issue by trincao** [cctbx/dxtbx#568]
Data read correctly with `dials 3.8.x` but fail with latest dials release installed at Diamond (3.11.2)

```
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v3-11-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 242, in <module>
    run()
  File "/dls_sw/apps/dials/dials-v3-11-2/conda_base/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/dls_sw/apps/dials/dials-v3-11-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 236, in run
    results = do_spotfinding(experiments, params)
  File "/dls_sw/apps/dials/dials-v3-11-2/build/../modules/dials/src/dials/command_line/find_spots.py", line 127, in do_spotfinding
    reflections = flex.reflection_table.from_observations(experiments, params)
  File "/dls_sw/apps/dials/dials-v3-11-2/modules/dials/src/dials/array_family/flex_ext.py", line 179, in from_observations
    return spotfinder.find_spots(experiments)
  File "/dls_sw/apps/dials/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 702, in find_spots
    table, hot_mask = self._find_spots_in_imageset(imageset)
  File "/dls_sw/apps/dials/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 815, in _find_spots_in_imageset
    r, h = extract_spots(imageset[j0:j1])
  File "/dls_sw/apps/dials/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 415, in __call__
    return self._find_spots(imageset)
  File "/dls_sw/apps/dials/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 517, in _find_spots
    result = function(task)
  File "/dls_sw/apps/dials/dials-v3-11-2/modules/dials/src/dials/algorithms/spot_finding/finder.py", line 79, in __call__
    mask = self.imageset.get_mask(index)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Internal Error: /scratch/jenkins_agent/workspace/dials_patch_release/build_dials/modules/dxtbx/src/dxtbx/imageset.h(858): DXTBX_ASSERT(m1.accessor().all_eq(m2.accessor())) failure.
```

Is the new error message. With @graeme-winter who thinks this is a regression where the old FormatNexusEigerDLS used to sometimes switch the detector dimensions to be correct wheras FormatNXmx or whatever does not. 

That was useful: please restore

**Comment by trincao** [comment]
Example of offending data set

```
/dls/mx/data/cm28161/cm28161-4/210929/Ld14/grid3/213kev/x13/x13_1_master.h5
```
