### ISSUE TITLE
Flumpy (?) long vs int issue on Windows

### ISSUE THREAD

**Issue by rjgildea** [cctbx/dxtbx#593]
The following error from the dxtbx conda feedstock Windows build is (I think) likely an issue with flumpy incorrectly converting numpy ints to `flex.long` rather than `flex.int` as on other platforms. This hasn't been noticed till now because [we haven't had working Windows CI for some time](https://github.com/cctbx/dxtbx/issues/396).
```
_______________________ test_get_raw_data_single_panel ________________________

nxdata_example = <HDF5 file " " (mode r+)>

    def test_get_raw_data_single_panel(nxdata_example):
        det = dxtbx.nexus.nxmx.NXdetector(nxdata_example["/entry/instrument/detector"])
        nxdata = dxtbx.nexus.nxmx.NXdata(nxdata_example["/entry/data"])
        for i in range(3):
            raw_data = dxtbx.nexus.get_raw_data(nxdata, det, i)
            assert len(raw_data) == 1
>           assert isinstance(raw_data[0], flex.int)
E           AssertionError: assert False
E            +  where False = isinstance(<scitbx_array_family_flex_ext.long object at 0x00000280E923DB40>, <class 'scitbx_array_family_flex_ext.int'>)
E            +    where <class 'scitbx_array_family_flex_ext.int'> = flex.int

dxtbx\tests\nexus\test_build_dxtbx_models.py:570: AssertionError
```

**Comment by rjgildea** [comment]
With dxtbx installed via mamba on Windows:
```
python
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dxtbx
>>> import numpy as np
>>> a = np.array([1, 2, 3])
>>> a.dtype
dtype('int32')
>>> from dxtbx import flumpy
>>> flumpy.from_numpy(a)
<scitbx_array_family_flex_ext.long object at 0x00000213B428A640>
```

**Comment by rjgildea** [comment]
In contrast on Linux:
```
$ dials.python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from dxtbx import flumpy
>>> a = np.array([1, 2, 3])
>>> flumpy.from_numpy(a.astype(np.int32))
<scitbx_array_family_flex_ext.int object at 0x7f0c35897290>
>>> flumpy.from_numpy(a.astype(np.int_))
<scitbx_array_family_flex_ext.long object at 0x7f0c35897400>
>>> flumpy.from_numpy(a.astype(np.intc))
<scitbx_array_family_flex_ext.int object at 0x7f0c35897290>
```

**Comment by ndevenish** [comment]
Other than failing the assert, is it actually a problem that this changes? With int32, at least we are being consistent in int capacity

**Comment by rjgildea** [comment]
The intention of that function is that a numpy integer array gets returned as a `flex.int`. Downstream C++ code has the expectation that data are either `float`, `double` or `int`:
https://github.com/cctbx/dxtbx/blob/d1ac171c6083ad9d17a5a6ad4368afc414579a2b/src/dxtbx/imageset.h#L464-L475
Forcing the data type to `flex.long` by changing line 501 of `dxtbx/nexus/__init__.py` to
```
        data_np = data_np.astype(np.int_, copy=False)
```
results in an error:
```
$ dials.image_viewer /dls/i03/data/2022/cm31105-5/TestInsulin/ins_20/ins_20_5_master.h5 
Traceback (most recent call last):
  File "/path/to/cctbx/build/../modules/dials/src/dials/command_line/image_viewer.py", line 217, in <module>
    run()
  File "/path/to/cctbx/conda_base/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/path/to/cctbx/build/../modules/dials/src/dials/command_line/image_viewer.py", line 213, in run
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/path/to/cctbx/build/../modules/dials/src/dials/command_line/image_viewer.py", line 178, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/path/to/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_wrap.py", line 82, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/path/to/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 638, in load_image
    super().load_image(
  File "/path/to/cctbx/modules/dials/src/dials/util/image_viewer/slip_viewer/frame.py", line 428, in load_image
    self.pyslip.tiles.set_image(
  File "/path/to/cctbx/modules/dials/src/dials/util/image_viewer/slip_viewer/tile_generation.py", line 70, in set_image
    self.raw_image.set_image_data(get_image_data(self.raw_image))
  File "/path/to/cctbx/modules/dials/src/dials/util/image_viewer/spotfinder_frame.py", line 1069, in get_image_data
    image_data = image.get_image_data()
  File "/path/to/cctbx/modules/dials/src/dials/util/image_viewer/slip_viewer/frame.py", line 57, in get_image_data
    return self.image_set.get_corrected_data(self.index)
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: dxtbx Error: /path/to/cctbx/modules/dxtbx/src/dxtbx/imageset.h(473): Unknown type long
```
