### ISSUE TITLE
Guess what you can't pickle? dxtbx_masking_ext.GoniometerShadowMasker

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#64]
https://github.com/xia2/xia2/issues/316 is actually caused by 

```
Error: Pickling of "dxtbx_masking_ext.GoniometerShadowMasker" instances is not enabled
```

At 

```
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 372, in run
    xia2_main()
  File "/Users/graeme/svn/cctbx/build/../modules/xia2/command_line/xia2_main.py", line 54, in xia2_main
    CommandLine = get_command_line()
  File "/Users/graeme/svn/cctbx/modules/xia2/Applications/xia2_main.py", line 115, in get_command_line
    CommandLine.set_xinfo(xinfo)
  File "/Users/graeme/svn/cctbx/modules/xia2/Handlers/CommandLine.py", line 523, in set_xinfo
    self._xinfo = XProject(xinfo)
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XProject.py", line 36, in __init__
    self.setup_from_xinfo_file(xinfo_file)
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XProject.py", line 348, in setup_from_xinfo_file
    excluded_regions=sweep_info.get("excluded_regions", []),
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XWavelength.py", line 267, in add_sweep
    excluded_regions=excluded_regions,
  File "/Users/graeme/svn/cctbx/modules/xia2/Schema/XSweep.py", line 231, in __init__
    self._imageset = copy.deepcopy(imagesets[0])
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 328, in _reconstruct
    args = deepcopy(args, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
RuntimeError: Pickling of "dxtbx_masking_ext.GoniometerShadowMasker" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)
```

Guess should be trivial to mock up a failing test

**Comment by graeme-winter** [comment]
@jmp1985 or @ndevenish any chance you could look at this? Could probably do way quicker than others 🙂

**Comment by jmp1985** [comment]
I've now fixed this in commit https://github.com/dials/dxtbx/commit/b2abc048919ab8dec46a1a14adc4c044a4bf3627

**Comment by graeme-winter** [comment]
@jmp1985 verified thank you for the quick work
