### ISSUE TITLE
can't import snowflake CBF

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/dxtbx#66]
```
$ dials.import /dls/i04/data/2019/mx19301-31/tmp/s2c/3d1ecaea-1703-45ba-b6f2-109a852d83a1/*1.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.545-g277d1717e
Traceback (most recent call last):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/dials_import.py", line 909, in <module>
    halraiser(e)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/dials_import.py", line 907, in <module>
    script.run()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/build/../modules/dials/command_line/dials_import.py", line 751, in run
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/options.py", line 838, in parse_args
    quick_parse=quick_parse,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/options.py", line 550, in parse_args
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/options.py", line 229, in __init__
    format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dials/util/options.py", line 295, in try_read_experiments_from_images
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/model/experiment_list.py", line 496, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/datablock.py", line 1027, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/datablock.py", line 484, in __init__
    format_kwargs=format_kwargs,
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/datablock.py", line 540, in _extract_file_metadata
    fmt = format_class(filename, **format_kwargs)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/FormatCBFMiniEigerDLS16MSN160.py", line 54, in __init__
    super(FormatCBFMiniEigerDLS16MSN160, self).__init__(image_file, **kwargs)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/FormatCBFMiniEiger.py", line 52, in __init__
    FormatCBFMini.__init__(self, image_file, **kwargs)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/FormatCBFMini.py", line 70, in __init__
    FormatCBF.__init__(self, image_file, **kwargs)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/FormatCBF.py", line 66, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/Format.py", line 146, in __init__
    self.setup()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/Format.py", line 162, in setup
    detector_instance = self._detector()
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/FormatCBFMiniEiger.py", line 130, in _detector
    for f0, f1, s0, s1 in determine_eiger_mask(detector):
  File "/dls/science/groups/scisoft/DIALS/CD/now/build_dials/modules/dxtbx/format/FormatPilatusHelpers.py", line 212, in determine_eiger_mask
    n_fast, remainder = divmod(size[0], detector.module_size_fast)
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'module_size_fast'
```
whereas
```
$ dials.import /dls/i04/data/2019/mx19301-31/tmp/s2c/3d1ecaea-1703-45ba-b6f2-109a852d83a1/*1.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 1.14.8-ge45eb7d1a-release
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatCBFMiniEigerDLS16MSN160.FormatCBFMiniEigerDLS16MSN160'>
  num images: 1
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
```

**Comment by graeme-winter** [comment]
Fixed in https://github.com/cctbx/dxtbx/commit/7d3180e25e8c73c414f51e4cf9059fcfa97b5c12
