### ISSUE TITLE
Errors importing gzipped cbf

### ISSUE THREAD

**Issue by ndevenish** [cctbx/dxtbx#72]
I'm seeing errors when trying to import the gzipped version of cbf files that work perfectly on their own. Example file: `/dls/science/users/mep23677/cbfgz_dxtbx72_0001.cbf`. Still poking this myself but it shows in 1.14 and 2.0. Curiously, taking the tutorial C2Sum betalactamase data doesn't exhibit this; even decompressing and recompressing works with those, so maybe something to do with `FormatCBFFullPilatus`?
```
$ dials.import cbfgz_dxtbx72_0001.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 1.14.9-g0c59d74b8-release
...
Writing datablocks to datablock.json

$ gzip cbfgz_dxtbx72_0001.cbf
$ dials.import cbfgz_dxtbx72_0001.cbf.gz
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 1.14.9-g0c59d74b8-release
CBFlib: warning input line 1 (1) -- invalid character
CBFlib: warning input line 1 (2) -- invalid character
CBFlib: warning input line 1 (3) -- invalid character
CBFlib: warning input line 1 (4) -- invalid character
CBFlib: warning input line 1 (6) -- invalid character
CBFlib: warning input line 1 (9) -- invalid character
CBFlib: warning input line 1 (23) -- invalid character
CBFlib: warning input line 1 (24) -- invalid character
CBFlib: warning input line 1 (26) -- invalid character
CBFlib: warning input line 1 (28) -- invalid character
CBFlib: warning input line 1 (30) -- invalid character
CBFlib: warning input line 1 (1) -- no data block
CBFlib: error input line 1 (1) -- syntax error
CBFlib: warning input line 1 (1) -- data block (null) ends with no content
Traceback (most recent call last):
  File "/dls_sw/apps/dials/dials-v1-14-9/build/../modules/dials/command_line/dials_import.py", line 883, in <module>
    halraiser(e)
  File "/dls_sw/apps/dials/dials-v1-14-9/build/../modules/dials/command_line/dials_import.py", line 881, in <module>
    script.run()
  File "/dls_sw/apps/dials/dials-v1-14-9/build/../modules/dials/command_line/dials_import.py", line 738, in run
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/dials/util/options.py", line 899, in parse_args
    quick_parse=quick_parse,
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/dials/util/options.py", line 592, in parse_args
    format_kwargs=format_kwargs,
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/dials/util/options.py", line 233, in __init__
    format_kwargs,
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/dials/util/options.py", line 305, in try_read_datablocks_from_images
    format_kwargs=format_kwargs,
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/datablock.py", line 1091, in from_filenames
    format_kwargs=format_kwargs,
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/datablock.py", line 545, in __init__
    format_kwargs=format_kwargs,
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/datablock.py", line 605, in _extract_file_metadata
    fmt = format_class(filename, **format_kwargs)
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/FormatCBFFullPilatus.py", line 41, in __init__
    FormatCBFFull.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/FormatCBFFull.py", line 45, in __init__
    FormatCBF.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/FormatCBF.py", line 58, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/Format.py", line 203, in __init__
    self.setup()
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/Format.py", line 216, in setup
    goniometer_instance = self._goniometer()
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/FormatCBFFull.py", line 68, in _goniometer
    return self._goniometer_factory.imgCIF_H(self._get_cbf_handle())
  File "/dls_sw/apps/dials/dials-v1-14-9/modules/cctbx_project/dxtbx/format/FormatCBFFull.py", line 62, in _get_cbf_handle
    self._cbf_handle.read_widefile(self._image_file, pycbf.MSG_DIGEST)
  File "/dls_sw/apps/dials/dials-v1-14-9/build/lib/pycbf.py", line 3285, in read_widefile
    return _pycbf.cbf_handle_struct_read_widefile(self, filename, headers)
Exception: CBFlib Error(s): CBF_FORMAT
```

**Comment by ndevenish** [comment]
There was a test added for this in https://github.com/cctbx/cctbx_project/commit/e6ae0e03afe87500ad573b2fde42dca9334ea2e5 - this never worked and was never run, and was removed in https://github.com/cctbx/dxtbx/commit/dc187ba2fd2e30a5711f6675cac4ed463f628da7, so it could just be that this has _only_ ever worked on MiniCBF's?

**Comment by graeme-winter** [comment]
Known thing - full CBF files cannot be read compressed, as cbflib does the file opening and we cannot pass in a file like object

**Comment by graeme-winter** [comment]
Yes, only works with miniCBF where we wrote our own parser - propose closing

**Comment by ndevenish** [comment]
So policy is essentially,
> All cbf files are equal,
> but some are more equal than others.

Will try to poke and fail to understand in FullCBF. It's not exactly something we advertise but we do run the tutorials with compressed cbf files so someone might try to use it (plus, _Exception_)

**Comment by rjgildea** [comment]
Does it work for other non-CBF image files where we do the file reading ourselves? If so it might be worth re-introducing a form of the test originally added in https://github.com/cctbx/cctbx_project/commit/e6ae0e03afe87500ad573b2fde42dca9334ea2e5, and now we use modern tools like pytest we can selectively mark expected failures (i.e. full CBF).
