### ISSUE TITLE
Support for non Diamond Eiger 2X 16M

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#74]
DECTRIS Eiger 2 16M at SLS is currently giving:

```
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/show.py", line 629, in <module>
    run(sys.argv[1:])
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/show.py", line 192, in run
    params, options = parser.parse_args(show_diff_phil=True)
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 853, in parse_args
    quick_parse=quick_parse,
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 565, in parse_args
    load_models=load_models,
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 231, in __init__
    load_models,
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 304, in try_read_experiments_from_images
    load_models=load_models,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 496, in from_filenames
    format_kwargs=format_kwargs,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1030, in from_filenames
    format_kwargs=format_kwargs,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 474, in __init__
    fmt, filename, format_kwargs=format_kwargs
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 668, in _create_single_file_imageset
    return format_class.get_imageset(abspath(filename), format_kwargs=format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 159, in get_imageset
    reader = cls.get_reader()(filenames, num_images=num_images, **format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 23, in __init__
    self._num_images = self.read_num_images()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatMultiImage.py", line 39, in read_num_images
    format_instance = self.format_class.get_instance(self._filename, **self.kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 255, in get_instance
    Class._current_instance_ = Class(filename, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatNexus.py", line 22, in __init__
    FormatHDF5.__init__(self, image_file, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatHDF5.py", line 14, in __init__
    Format.__init__(self, image_file, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 146, in __init__
    self.setup()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 156, in setup
    self._start()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatNexus.py", line 34, in _start
    self._reader = reader = NXmxReader(self._image_file)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/nexus.py", line 883, in __init__
    % (filename, "\n".join(self.errors))
RuntimeError: 
        Error reading NXmxfile: /Users/graeme/data/sls-eiger2/insu_15_master.h5
          No NXmx entries in file

        The following errors occurred:

        No NXbeam in /entry/sample
No NXsample in /entry
```

type errors in dials/master - should make them work or identify what is missing.

**Comment by graeme-winter** [comment]
Comparison with Diamond files: `/entry/definition`

```
Grey-Area i04-eiger-small :) $ ~/svn/cctbx/base/bin/h5dump -d /entry/definition Therm_6_2_master.h5 
HDF5 "Therm_6_2_master.h5" {
DATASET "/entry/definition" {
   DATATYPE  H5T_STRING {
      STRSIZE 4;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "NXmx"
   }
}
}
```

vs. 

```
Grey-Area sls-eiger2 :( $ ~/svn/cctbx/base/bin/h5dump -d /entry/definition insu_15_master.h5 
HDF5 "insu_15_master.h5" {
DATASET "/entry/definition" {
   DATATYPE  H5T_STRING {
      STRSIZE 5;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "NXmx"
   }
   ATTRIBUTE "version" {
      DATATYPE  H5T_STRING {
         STRSIZE 4;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "1.4"
      }
   }
}
}
```

=> good enough

**Comment by graeme-winter** [comment]
Right now working through implementation of `group.visititems` in `h5py` - suspect that this does not resolve soft links

**Comment by graeme-winter** [comment]
This seems to be complex...

https://support.hdfgroup.org/HDF5/doc/RM/RM_H5O.html#Object-Visit

```
        with phil:
            def proxy(name):
                """ Use the text name of the object, not bytes """
                name = self._d(name)
                return func(name, self[name])
            return h5o.visit(self.id, proxy)
```

The Python bindings are only using the h5o interface not the h5l ones? So may/will not recurse to soft links... 🤔

**Comment by graeme-winter** [comment]
Yes... visititems does _not_ traverse softlinks

```
>>> def visitor(name, obj):
...   if hasattr(obj, "keys"):
...     print name, obj.keys()
...   else:
...     print name
```

```
>>> s.visititems(visitor)
depends_on
goniometer [u'omega', u'omega_end', u'omega_range_average', u'omega_range_total']
goniometer/omega
goniometer/omega_end
goniometer/omega_range_average
goniometer/omega_range_total
transformations [u'omega', u'omega_end', u'omega_range_average', u'omega_range_total', u'translation']
transformations/omega
transformations/omega_end
transformations/omega_range_average
transformations/omega_range_total
transformations/translation
>>> s["beam"]
<HDF5 group "/entry/sample/beam" (1 members)>

```

**Comment by graeme-winter** [comment]
For reference this is a known thing: 

https://github.com/h5py/h5py/issues/671

Possibly need our own visitor pattern implementation (probably relatively trivial)

**Comment by graeme-winter** [comment]
Looks like saturation value missing from example data set i.e. `/entry/instrument/detector/saturation_value`

**Comment by graeme-winter** [comment]
Still open as the interpreted geometry is complete nonsense.

**Comment by graeme-winter** [comment]
```
dials.import ../insu_15_master.h5 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.732-g17f531a27
The following parameters have been modified:

input {
  experiments = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexus'>
  num images: 900
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing experiments to imported.expt
Grey-Area-2 run :) $ dials.geometry_viewer imported.expt 
```

gives:
![Screen Shot 2019-08-28 at 14 25 18](https://user-images.githubusercontent.com/1241716/63859722-b975d100-c99f-11e9-86aa-3a285a059b1e.png)

**Comment by graeme-winter** [comment]
Beam centre x, y are ~ sensible:

```
Grey-Area-2 run :) $ h5dump -d /entry/instrument/detector/beam_center_x ../insu_15_master.h5 
HDF5 "../insu_15_master.h5" {
DATASET "/entry/instrument/detector/beam_center_x" {
   DATATYPE  H5T_IEEE_F64LE
   DATASPACE  SCALAR
   DATA {
   (0): 2120.75
   }
   ATTRIBUTE "units" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "pixel"
      }
   }
}
}
Grey-Area-2 run :) $ h5dump -d /entry/instrument/detector/beam_center_y ../insu_15_master.h5 
HDF5 "../insu_15_master.h5" {
DATASET "/entry/instrument/detector/beam_center_y" {
   DATATYPE  H5T_IEEE_F64LE
   DATASPACE  SCALAR
   DATA {
   (0): 2145.94
   }
   ATTRIBUTE "units" {
      DATATYPE  H5T_STRING {
         STRSIZE 6;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "pixel"
      }
   }
}
}

```

**Comment by graeme-winter** [comment]
With the additional changes `xia2` works fine:

```For AUTOMATIC/DEFAULT/NATIVE                 Overall    Low     High
High resolution limit                           1.44    3.91    1.44
Low resolution limit                           31.83   31.84    1.46
Completeness                                  100.0   100.0   100.0
Multiplicity                                    9.7     9.9     8.6
I/sigma                                        21.1    97.3     0.9
Rmerge(I)                                     0.044   0.020   1.040
Rmerge(I+/-)                                  0.041   0.018   0.964
Rmeas(I)                                      0.047   0.021   1.106
Rmeas(I+/-)                                   0.046   0.021   1.098
Rpim(I)                                       0.015   0.007   0.375
Rpim(I+/-)                                    0.020   0.009   0.519
CC half                                       0.998   0.998   0.700
Wilson B factor                              21.507
Anomalous completeness                        100.0    99.8   100.0
Anomalous multiplicity                          5.1     5.5     4.4
Anomalous correlation                         0.014  -0.010  -0.010
Anomalous slope                               0.720
Total observations                           140742    7718    6242
Total unique                                  14437     778     725
Assuming spacegroup: I 2 3
Unit cell (with estimated std devs):
77.96239(17) 77.96239(17) 77.96239(17)
90.0         90.0         90.0        
```

Will be included in upcoming release.
