### ISSUE TITLE
Errors importing miniCBF from dlsnxs2cbf

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/dxtbx#79]
[import.zip](https://github.com/cctbx/dxtbx/files/3558919/import.zip)

File in attached from dlsnxs2cbf - used to import fine - now gives:

```
Grey-Area dlsnxs2cbf :( $ dials.import therm_0001.cbf 
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.757-gacb12b9ec
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 902, in <module>
    script.run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/dials_import.py", line 747, in run
    params, options = self.parser.parse_args(args=args, show_diff_phil=False)
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 853, in parse_args
    quick_parse=quick_parse,
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 565, in parse_args
    load_models=load_models,
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 231, in __init__
    load_models,
  File "/Users/graeme/svn/cctbx/modules/dials/util/options.py", line 304, in try_read_experiments_from_images
    load_models=load_models,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/model/experiment_list.py", line 506, in from_filenames
    format_kwargs=format_kwargs,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 1030, in from_filenames
    format_kwargs=format_kwargs,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 487, in __init__
    format_kwargs=format_kwargs,
  File "/Users/graeme/svn/cctbx/modules/dxtbx/datablock.py", line 543, in _extract_file_metadata
    fmt = format_class(filename, **format_kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatCBFMiniEigerDLS16MSN160.py", line 50, in __init__
    super(FormatCBFMiniEigerDLS16MSN160, self).__init__(image_file, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatCBFMini.py", line 66, in __init__
    super(FormatCBFMini, self).__init__(image_file, **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatCBF.py", line 65, in __init__
    super(FormatCBF, self).__init__(str(image_file), **kwargs)
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 146, in __init__
    self.setup()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/Format.py", line 162, in setup
    detector_instance = self._detector()
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatCBFMiniEiger.py", line 114, in _detector
    for f0, f1, s0, s1 in determine_eiger_mask(detector):
  File "/Users/graeme/svn/cctbx/modules/dxtbx/format/FormatPilatusHelpers.py", line 212, in determine_eiger_mask
    n_fast, remainder = divmod(size[0], detector.module_size_fast)
AttributeError: Please report this error to dials-support@lists.sourceforge.net: 'NoneType' object has no attribute 'module_size_fast'
```

suspect related to logical cleanup from @rjgildea.

cbf file in zip file attached.

**Comment by rjgildea** [comment]
Please can we add an example image to dials-data? Lack of test coverage does not help here.

**Comment by graeme-winter** [comment]
Of course. It _should_ read compressed as miniCBF (independent of @ndevenish work) and is 168k as gzip so could simply add? Or could push the entire sweep for other tests too... but would prefer if someone else executes this more competently than I would (can provide data).

**Comment by rjgildea** [comment]
I'm not sure this is related to recent dxtbx changes. I get the same error even rolling dxtbx back to June. When did this last work for you on this file?

**Comment by graeme-winter** [comment]
Good question, no answer, I will investigate further then.

**Comment by graeme-winter** [comment]
This problem is a different problem to the one I thought it was...

**Comment by rjgildea** [comment]
Possibly related? https://github.com/cctbx/dxtbx/commit/b21bf4c47739bff6387428d45ab00267669bcedf#diff-1ddcb92ade31c8fbd370001f9b29a7d9

**Comment by graeme-winter** [comment]
Actually I think not - more likely https://github.com/cctbx/dxtbx/commit/b3c9a071

@Anthchirp _may_ have introduced a regression here
